<?php
printf(
    '<button type="button" class="btn btn-xs btn-default"  data-container="body" data-toggle="modal" data-target="#%s_errors_modal">View Error</button>',
    $this->escapeHtmlAttr($this->field->getHtmlId())
);
?>

<div class="modal fade" id="<?php echo $this->escapeHtmlAttr($this->field->getHtmlId());?>_errors_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Exception thrown when sorting <strong><?php echo $this->escapeHtml($this->field->getId());?></strong></h4>
            </div>
            <div class="modal-body">
                <pre><?php echo $this->escapeHtml($this->message);?></pre>
            </div>
        </div>
    </div>
</div>
