<?php if ($this->invalidSubmission):?>
<div class="alert alert-danger">
    Some errors were found in your submission.  Please double-check and try again.
</div>
<?php endif;?>

<?php
echo $this->bootstrapBreadcrumbs([
    ['title' => $this->component->getTitle(), 'href' => $this->adminUrl('index')],
    ['title' => ($this->isNew ? 'Add' : 'Edit') . ' ' . $this->model->getSingularTitle(), 'active' => true]
]);
?>

<?php if (!$this->rowEditor->isNew() && $this->rowEditor->hasDeleteField()):?>

<?php
$params = [];

foreach ($this->model->getPrimaryKey() as $field) {
    $params[$field] = $this->request->getQuery($field);
}
?>

<div class="navbar navbar-default" role="navigation">
    <div class="navbar-right navbar-right-btn-group">
        <a class="navbar-btn btn btn-danger btn-delete" data-message="Are you sure you want to delete this <?php echo $this->escapeHtmlAttr(strtolower($this->model->getSingularTitle()));?>?" data-href="<?php echo $this->escapeHtmlAttr($this->adminUrl('delete', $params));?>" data-redirect="<?php echo $this->escapeHtmlAttr($this->adminUrl('index'));?>">Delete This <?php echo $this->escapeHtml($this->model->getSingularTitle());?></a>
    </div>
</div>
<?php $this->headScript()->appendFile($this->bowerUrl('/dewdrop/www/js/delete-button.js'));?>

<?php endif;?>

<?php
echo $this->bootstrapForm(
    $this->fields,
    $this->rowEditor->getInputFilter()
);
?>
