<?php

/* @var $view \Dewdrop\View\View */
$view = $this;
?>

<?php
if ($this->bulkActionFailureMessage) {
    printf(
        '<div class="alert alert-danger">%s</div>',
        $this->escapeHtml($this->bulkActionFailureMessage)
    );
}

echo $this->adminComponentNav(
    $this->component,
    [
        'createUrl' => $this->createUrl
    ]
);

echo $this->bootstrapFilterForm()->adminPanel($this->component);
?>

<?php
echo $this->partial(
    'index-keyboard-shortcuts.phtml',
    array(
        'componentTitle' => $this->component->getTitle(),
        'singularTitle'  => $this->singularTitle
    )
);
?>

<?php
/* @var $fields \Dewdrop\Fields */

$renderer = $this->tableCellRenderer();
$fields   = $this->fields->getVisibleFields(array($this->groupingFilter, $this->visibilityFilter));
$pkey     = $this->listing->getPrimaryKey()->getName();

$rowActionArgs = array(
    'renderer'  => $renderer,
    'field'     => $fields->getIterator()->current(),
    'title'     => $this->singularTitle,
    'urlFields' => $pkey
);

if ($this->permissions->can('edit')) {
    $rowActionArgs['edit'] = $this->adminUrl('edit', array($pkey => '%s'));
}

if ($this->permissions->can('view')) {
    $rowActionArgs['view'] = $this->adminUrl('view', array($pkey => '%s'));
}


$this->bootstrapRowActions()->assignCallback($rowActionArgs);

$selectFilter  = $this->listing->getSelectModifierByName('SelectFilter');
$listingData   = $this->listing->fetchData($this->groupingFilter->apply($this->fields));
$totalRowCount = $this->listing->getTotalRowCount();

if ($this->isSortable) {
    $sortField = $this->component->getSortField();

    $this->tableSortHandle()->assignToField(
        $sortField,
        $renderer,
        $this->listing->getPrimaryKey()->getName()
    );

    echo $this->tableSortHandle()->open($this->adminUrl('sort-listing'));
}

if ($this->bulkActions) {
    $fields->prepend($this->bulkActionCheckboxField($this->bulkActions, $renderer));

    echo $this->bulkActionForm()->open();
}

if (0 === $totalRowCount && $selectFilter->hasFilters()) {
    printf(
        '<div class="alert alert-warning">No %s found matching your filters.  Please try again.</div>',
        $this->escapeHtml(strtolower($this->pluralTitle))
    );
} else {
    echo $this->bootstrapTable(
        $fields,
        $listingData,
        $renderer,
        $this->listing->getSelectModifierByName('SelectSort')
    );
}

if ($this->isSortable) {
    echo $this->tableSortHandle()->close();
}

/* @var $paginationHelper \Dewdrop\Fields\Helper\SelectPaginate */
$paginationHelper = $this->listing->getSelectModifierByName('SelectPaginate');

if ($this->bulkActions) {
    echo $this->bulkActionForm()->close(
        $this->bulkActions,
        $totalRowCount,
        ($paginationHelper->isEnabled() ? $paginationHelper->getPageSize() : $totalRowCount),
        $this->pluralTitle
    );
}

echo $this->pagination(
    $totalRowCount,
    ($paginationHelper->isEnabled() ? $paginationHelper->getPageSize() : $totalRowCount),
    $paginationHelper->getPage(),
    (1 === $totalRowCount ? $this->singularTitle : $this->pluralTitle)
);

echo $this->bootstrapColumnsModal(
    $this->fields->getVisibleFields($this->groupingFilter),
    $this->fields->getVisibleFields($this->visibilityFilter),
    $this->adminUrl('adjust-visibility'),
    $this->visibilityFilter->canBeFilteredByUser()
);

$this->headScript()->appendFile($this->bowerUrl('/dewdrop/www/js/listing-keyboard-shortcuts.js'));
?>
