<?php

/* @var $view \Dewdrop\View\View */
$view = $this;
?>

<?php
if ($this->bulkActionFailureMessage) {
    printf(
        '<div class="alert alert-danger">%s</div>',
        $this->escapeHtml($this->bulkActionFailureMessage)
    );
}

echo $this->adminComponentNav(
    $this->component,
    [
        'createUrl'              => $this->createUrl,
        'deletedRecordsModifier' => $this->deletedRecordsModifier
    ]
);

echo $this->bootstrapFilterForm()->adminPanel($this->component);
?>

<?php
echo $this->partial(
    'index-keyboard-shortcuts.phtml',
    array(
        'componentTitle' => $this->component->getTitle(),
        'singularTitle'  => $this->singularTitle
    )
);

// Start table

$renderer = $this->tableCellRenderer();
$fields   = $this->fields->getVisibleFields(array($this->groupingFilter, $this->visibilityFilter));
$pkey     = $this->listing->getPrimaryKey()->getName();

$rowActionArgs = array(
    'renderer'  => $renderer,
    'field'     => $fields->getIterator()->current(),
    'title'     => $this->singularTitle,
    'urlFields' => $pkey
);

if ($this->permissions->can('edit')) {
    $rowActionArgs['edit'] = $this->adminUrl('edit', array($pkey => '%s'));
}

if ($this->permissions->can('view')) {
    $rowActionArgs['view'] = $this->adminUrl('view', array($pkey => '%s'));
}

$this->bootstrapRowActions()->assignCallback($rowActionArgs);

$selectFilter  = $this->listing->getSelectModifierByName('SelectFilter');

if ($this->isSortable) {
    $sortField = $this->component->getSortField();

    $this->tableSortHandle()->assignToField(
        $sortField,
        $renderer,
        $this->listing->getPrimaryKey()->getName()
    );

    echo $this->tableSortHandle()->open($this->adminUrl('sort-listing'));
}

if ($this->bulkActions) {
    $fields->prepend($this->bulkActionCheckboxField($this->bulkActions, $renderer));

    echo $this->bulkActionForm()->open();
}

if ($this->deletedRecordsModifier && $this->deletedRecordsModifier->isShowingDeletedRecords()) {
    printf(
        '<div class="alert alert-warning">Currently displaying deleted %s.</div>',
        $this->escapeHtml($this->pluralTitle)
    );
}

if (0 === $this->totalRowCount && $selectFilter->hasFilters()) {
    printf(
        '<div class="alert alert-warning">No %s found matching your filters.  Please try again.</div>',
        $this->escapeHtml(strtolower($this->pluralTitle))
    );
} else {
    echo $this->listing->renderTable(
        $this,
        $fields,
        $this->component,
        $renderer
    );
}

// End table

if ($this->isSortable) {
    echo $this->tableSortHandle()->close();
}

$totalRowCount = $this->listing->getTotalRowCount();

/* @var $paginationHelper \Dewdrop\Fields\Helper\SelectPaginate */
$paginationHelper = $this->listing->getSelectModifierByName('SelectPaginate');

if ($this->bulkActions) {
    echo $this->bulkActionForm()->close(
        $this->bulkActions,
        $totalRowCount,
        ($paginationHelper->isEnabled() ? $paginationHelper->getPageSize() : $totalRowCount),
        $this->pluralTitle
    );
}

$paginationTitle = (1 === $totalRowCount ? $this->singularTitle : $this->pluralTitle);

echo $this->listing->renderPagination(
    $this,
    $totalRowCount,
    $paginationTitle
);

echo $this->bootstrapColumnsModal(
    $this->fields->getVisibleFields($this->groupingFilter),
    $this->fields->getVisibleFields($this->visibilityFilter),
    $this->adminUrl('adjust-visibility'),
    $this->visibilityFilter->canBeFilteredByUser()
);

echo $this->listing->renderFooter($this, $fields, $paginationTitle);
?>
