<?php

/* @var $view \Dewdrop\View\View */
$view = $this;

$request = $view->getRequest();

?>
<nav class="navbar navbar-default navbar-admin-index" role="navigation">
    <div class="navbar-header">
        <?php if ($this->permissions->can('create')) :?>
        <a data-keyboard-role="create" href="<?php echo $this->escapeHtmlAttr($this->adminUrl('edit'));?>" class="btn btn-primary navbar-btn">Add <?php echo $this->escapeHtml($this->singularTitle);?></a>
        <?php endif;?>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#admin-index-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="admin-index-collapse">
        <?php if ($this->permissions->can('export')) :?>
        <a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('export', array('format' => 'csv')));?>" class="btn btn-link btn-link-first navbar-btn">Export</a>
        <?php endif;?>

        <?php if ($this->permissions->can('adjust-columns')) :?>
        <a href="#" data-toggle="modal" data-target="#adjust-columns-modal" class="btn btn-link navbar-btn">Adjust Columns</a>
        <?php endif;?>
        <div class="navbar-right navbar-right-btn-group">
            <div class="btn-group btn-group-justified">
                <div class="btn-group">
                    <?php if ($this->permissions->can('filter')) :?>
                    <button data-keyboard-role="filter" type="button" class="btn btn-default navbar-btn" data-toggle="collapse" data-target="#admin-filter-panel"><span class="glyphicon glyphicon-filter"></span> Filter</button>
                    <?php endif;?>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-default admin-btn-settings navbar-btn" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Settings <span class="caret"></span></button>
                    <ul class="dropdown-menu" role="menu">
                        <?php if ($this->permissions->can('custom-views')) :?>
                        <li><a href="#">Save Current View</a></li>
                        <li><a href="#">Manage Custom Views</a></li>
                        <?php endif;?>

                        <?php if ($this->permissions->can('sort-fields')) :?>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('sort-fields'));?>">Sort and Group Fields</a></li>
                        <?php endif;?>

                        <?php if ($this->permissions->can('notifications')) :?>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('notifications'));?>">Notifications</a></li>
                        <?php endif;?>

                        <li><a data-toggle="modal" data-target="#keyboard-shortcuts-modal" href="#">View Keyboard Shortcuts</a></li>

                        <?php if ($this->permissions->can('debug')):?>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation" class="dropdown-header"><span class="glyphicon glyphicon-wrench"></span> Dev Tools</li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-fields'));?>">View Fields</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-listing-sql', $request->getQuery()));?>">View Listing SQL</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-pages'));?>">View Pages</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-test-sorting'));?>">Test Sorting</a></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="admin-filter-panel" class="panel panel-default admin-filter-panel collapse">
    <div class="panel-body">
        <form action="" method="GET">
            <div class="text-muted">
                <small>
                    Find <?php echo $this->escapeHtml(strtolower($this->pluralTitle));?> matching
                    <select name="filter_operand">
                        <option value="all">all</option>
                        <option value="any">any</option>
                    </select>
                    of these filters.
                </small>
            </div>
            <fieldset>
                <div class="row">
                    <div class="col-sm-4">
                        <select class="form-control input-sm" name="filters[]">
                            <option value="" disabled="disabled" selected="selected">Select a field to filter by...</option>
                            <?php
                            foreach ($this->fields->getFilterableFields($this->groupingFilter) as $field) {
                                printf(
                                    '<option value="%s">%s</option>',
                                    $this->escapeHtmlAttr($field->getId()),
                                    $this->escapeHtml($field->getLabel())
                                );
                            }
                            ?>
                        </select>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-inline">
                            <span class="glyphicon glyphicon-arrow-right visible-xs"></span>
                            <input class="form-control input-sm" type="date" />
                            <div class="pull-right btn-group">
                                <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"></span></button>
                                <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-minus"></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="footer">
                <input type="submit" class="btn btn-success btn-sm" value="Apply Filters" />
                <a class="btn btn-link btn-sm" href="<?php echo $this->escapeHtmlAttr($this->adminUrl('index'));?>">Clear Filters</a>
            </div>
        </form>
    </div>
</div>

<?php
echo $this->partial(
    'index-keyboard-shortcuts.phtml',
    array(
        'componentTitle' => $this->component->getTitle(),
        'singularTitle'  => $this->singularTitle
    )
);
?>

<?php
$renderer = $this->tableCellRenderer();
$fields   = $this->fields->getVisibleFields(array($this->groupingFilter, $this->visibilityFilter));
$pkey     = $this->listing->getPrimaryKey()->getName();

$rowActionArgs = array(
    'renderer'  => $renderer,
    'field'     => $fields->getIterator()->current(),
    'title'     => $this->singularTitle,
    'urlFields' => $pkey
);

if ($this->permissions->can('edit')) {
    $rowActionArgs['edit'] = $this->adminUrl('edit', array($pkey => '%s'));
}

if ($this->permissions->can('view')) {
    $rowActionArgs['view'] = $this->adminUrl('view', array($pkey => '%s'));
}

$this->bootstrapRowActions()->assignCallback($rowActionArgs);

echo $this->bootstrapTable(
    $fields,
    $this->listing->fetchData($this->groupingFilter->apply($this->fields), $rowCount),
    $renderer,
    $this->listing->getSelectModifierByName('SelectSort')
);

echo $this->pagination(
    $rowCount,
    $this->listing->getSelectModifierByName('SelectPaginate')->getPageSize(),
    (((int) $request->getQuery('page')) ?: 1)
);

echo $this->bootstrapColumnsModal(
    $this->fields->getVisibleFields($this->groupingFilter),
    $this->fields->getVisibleFields($this->visibilityFilter),
    $this->adminUrl('adjust-visibility')
);

$this->headScript()->appendFile($this->bowerUrl('/dewdrop/www/js/listing-keyboard-shortcuts.js'));
?>
