<ol class="breadcrumb">
    <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('index'));?>"><?php echo $this->escapeHtml($this->component->getTitle());?></a></li>
    <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('notifications'));?>">Notifications</a></li>
    <li class="active"><?php echo $this->escapeHtml($this->breadcrumbTitle . ' Subscription');?></li>
</ol>

<div class="page-header">
    <h1><span class="glyphicon glyphicon-envelope"></span> Notifications</h1>
</div>

<?php
$title = strtolower($this->componentModel->getPluralTitle());

$this->fields
    ->get('dewdrop_notification_subscriptions:when_added')
        ->setLabel("Send notifications when new {$title} are added")
    ->get('dewdrop_notification_subscriptions:when_edited')
        ->setLabel("Send notifications when {$title} are edited")
    ->get('dewdrop_notification_subscriptions:dewdrop_notification_frequency_id')
        ->setLabel('How often should notifications be sent?');

echo $this->bootstrapForm($this->fields, $this->rowEditor->getInputFilter());
?>
