<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"><?php echo $this->escapeHtml($this->title);?></h3></div>
    <div class="panel-body">
        <form action="/admin/forgot-password" method="post">

            <?php if ($this->error):?>
            <div class="alert alert-danger"><?php echo $this->escapeHtml($this->error); ?></div>
            <?php endif;?>

            <div class="alert alert-info">Enter the email address associated with your account.  We will email you a link that will allow you to reset your password.</div>

            <div class="form-group">
                <label for="username">Email Address</label>
                <input id="username" type="text" name="_username" class="form-control" autofocus value="" />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Reset Password</button>
            </div>
        </form>
    </div>
</div>
