<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"><?php echo ($this->headerHtml ?: $this->escapeHtml($this->title)); ?></h3></div>
    <div class="panel-body">
        <?php if (null !== $this->email_address): ?>
        <div class="alert alert-info">
            Check your email at <?php echo $this->escapeHtml($this->email_address); ?> for a message from us containing
            a link to reset your password. Thank you!
        </div>
        <?php else: ?>
        <form action="" method="post">

            <?php if ($this->error): ?>
            <div class="alert alert-danger"><?php echo $this->escapeHtml($this->error); ?></div>
            <?php endif; ?>

            <div class="alert alert-info">
                Enter the email address associated with your account.  We will email you a link that will allow you to
                reset your password.
            </div>

            <div class="form-group">
                <label for="email_address">Email Address</label>
                <input id="email_address" type="text" name="email_address" class="form-control" autofocus value="" />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Reset Password</button>
            </div>
        </form>
        <?php endif; ?>
    </div>
</div>
