<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo $this->escapeHtml($this->title);?></title>

        <?php
        $this->headLink()
            ->appendStylesheet($this->bowerUrl('/bootstrap/dist/css/bootstrap.min.css'))
            ->appendStylesheet($this->bowerUrl('/dewdrop/www/css/auth.css'));

        echo $this->headLink();
        echo $this->view->headLink();
        ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <?php
    $envClass = '';

    if (defined('APPLICATION_ENV')) {
        $envClass = 'env-' . APPLICATION_ENV;
    }
    ?>
    <body class="<?php echo $envClass;?>">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-4"></div>
            <div class="col-sm-6 col-md-4">
                <?php echo $this->content;?>
            </div>
            <div class="col-sm-3 col-md-4"></div>
        </div>

        <?php
        $this->headScript()
            ->appendFile($this->bowerUrl('/jquery/dist/jquery.min.js'))
            ->appendFile($this->bowerUrl('/bootstrap/dist/js/bootstrap.min.js'))
            ->appendFile($this->bowerUrl('/velocity/jquery.velocity.min.js'))
            ->appendFile($this->bowerUrl('/velocity/velocity.ui.js'));

        echo $this->headScript();
        echo $this->view->headScript();
        ?>
    </body>
</html>

