<?php if ($this->invalidToken): ?>
    <div class="alert alert-danger">Your password reset request could not be completed at this time.  Please try again.</div>
<?php else: ?>
<div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"><?php echo ($this->headerHtml ?: $this->escapeHtml($this->title));?></h3></div>
    <div class="panel-body">
        <form action="" method="post">
            <?php if ($this->error):?>
                <div class="alert alert-danger"><?php echo $this->escapeHtml($this->error); ?></div>
            <?php endif;?>

            <div class="form-group">
                <label for="username">Username</label>
                <div><?php echo $this->escapeHtml($this->user->get('username'));?></div>
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input id="password" type="password" name="password" class="form-control" autofocus
                       value="<?php echo $this->escapeHtmlAttr($this->password); ?>" />
            </div>

            <div class="form-group">
                <label for="confirm">Confirm Password</label>
                <input id="confirm" type="password" name="confirm" class="form-control" autofocus
                       value="<?php echo $this->escapeHtmlAttr($this->confirm); ?>" />
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Reset Password</button>
            </div>
        </form>
    </div>
</div>

<?php
if ($this->error) {
    $this->headScript()->appendFile($this->bowerUrl('/dewdrop/www/js/auth-error.js'));
}
?>
<?php endif;?>
