<ol class="breadcrumb">
    <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('index'));?>"><?php echo $this->escapeHtml($this->component->getTitle());?></a></li>
    <li class="active">Change Password</li>
</ol>

<?php
$this->fields->get('password')
    ->assignHelperCallback(
        'EditControl.Control',
        function ($helper, $view) {
            return $view->inputText(
                array(
                    'name'      => 'password',
                    'type'      => 'password',
                    'value'     => $this->request->getPost('password'),
                    'autofocus' => 'autofocus'
                )
            );
        }
    );

$this->fields->get('confirm_password')
    ->assignHelperCallback(
        'EditControl.Control',
        function ($helper, $view) {
            return $view->inputText(
                array(
                    'name'  => 'confirm_password',
                    'type'  => 'password',
                    'value' => $this->request->getPost('confirm_password')
                )
            );
        }
    );

echo $this->bootstrapForm($this->fields, $this->inputFilter);
?>
