<div class="ftr-logic-wrapper text-muted">
    <small>
        Find <?php echo $this->escapeHtml(strtolower($this->title ?: 'records'));?> matching
        <select data-chosen-exclude name="<?php echo $this->escapeHtmlAttr($this->paramPrefix);?>ftr-logic">
            <?php
            $operators = array('all', 'any');

            foreach ($operators as $operator) {
                if ($operator === $this->getRequest()->getQuery($this->paramPrefix . 'ftr-logic')) {
                    echo '<option value="' . $operator . '" selected="selected">' . $operator . '</option>';
                } else {
                    echo '<option value="' . $operator . '">' . $operator . '</option>';
                }
            }
            ?>
        </select>
        of these filters.
    </small>
</div>

<fieldset>
    <?php
    $config = array();

    foreach ($this->fields as $field) {
        $filterTypeAndOptions = $this->typeHelper->getTypeAndRelatedOptions($field);

        $config[] = array(
            'id'       => $field->getQueryStringId(),
            'label'    => $field->getLabel(),
            'type'     => $filterTypeAndOptions['type'],
            'defaults' => $this->defaultVars->getDefaultVars($field),
            'options'  => $filterTypeAndOptions['options']
        );
    }

    // Alphabetize filter fields by label
    usort(
        $config,
        function ($a, $b) {
            return strnatcasecmp($a['label'], $b['label']);
        }
    );
    ?>

    <script type="text/javascript">
        var <?php echo $this->paramPrefix;?>FILTER_FIELDS = <?php echo $this->encodeJsonHtmlSafe($config);?>;
        var <?php echo $this->paramPrefix;?>FILTER_VALUES = <?php echo $this->encodeJsonHtmlSafe($this->values);?>;
    </script>
</fieldset>

<?php if ($this->showButtons):?>
<div class="footer">
    <input type="submit" class="btn btn-success btn-sm" value="Apply Filters" />
    <a class="btn btn-link btn-sm" href="?">Clear Filters</a>

    <?php
    /* @var $request \Dewdrop\Request */
    $request = clone($this->request);
    $url     = $request->setQuery($this->paramPrefix . '-disable-pagination', 1)->getUrl();
    ?>
    <a class="btn btn-link btn-sm" href="<?php echo $this->escapeHtmlAttr($url);?>">
        Display All Matching <?php echo $this->escapeHtml($this->title ?: 'Records');?> on Single Page
    </a>
</div>
<?php endif;?>

<?php
if ($this->request->getQuery($this->prefix . 'sort')) {
    printf(
        '<input type="hidden" name="%s" value="%s" />',
        $this->escapeHtmlAttr($this->prefix . 'sort'),
        $this->escapeHtmlAttr($this->request->getQuery($this->prefix . 'sort'))
    );

    printf(
        '<input type="hidden" name="%s" value="%s" />',
        $this->escapeHtmlAttr($this->prefix . 'dir'),
        $this->escapeHtmlAttr($this->request->getQuery($this->prefix . 'dir'))
    );
}
?>

