<?php
use Dewdrop\Fields\Helper\SelectFilter;
?>

<?php
foreach ($this->getRequest()->getQuery() as $param => $value) {
    if (SelectFilter::isQueryStringParamNotRelatedToFiltering($param, $this->paramPrefix)) {
        printf(
            '<input type="hidden" name="%s" value="%s" />',
            $this->escapeHtmlAttr($param),
            $this->escapeHtmlAttr($value)
        );
    }
}
?>

<?php
if ($this->request->getQuery($this->prefix . 'sort')) {
    printf(
        '<input type="hidden" name="%s" value="%s" />',
        $this->escapeHtmlAttr($this->prefix . 'sort'),
        $this->escapeHtmlAttr($this->request->getQuery($this->prefix . 'sort'))
    );

    printf(
        '<input type="hidden" name="%s" value="%s" />',
        $this->escapeHtmlAttr($this->prefix . 'dir'),
        $this->escapeHtmlAttr($this->request->getQuery($this->prefix . 'dir'))
    );
}
?>

<?php echo $this->controls;?>
