<div class="modal fade" id="view-modal-<?php echo $this->escapeHtmlAttr($this->index);?>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">View <?php echo $this->escapeHtml($this->modalTitle);?></h4>
            </div>
            <div class="modal-body">

            </div>
        </div>
    </div>
</div>

