<ul class="<?php echo $this->escapeHtmlAttr(implode(' ', $this->classes));?>">
    <?php
    foreach ($this->options as $value => $title) {
        echo '<li>';

        printf(
            '<label for="%s_%s">',
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($value)
        );

        printf(
            '<input type="checkbox" name="%s[]" id="%s_%s" value="%s" %s />',
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($value),
            $this->escapeHtmlAttr($value),
            (in_array($value, $this->value) ? 'checked="checked"' : '')
        );

        echo ' ';
        echo $this->escapeHtml($title);
        echo '</label>';

        echo '</li>';
    }
    ?>
</ul>
