<select class="<?php echo $this->escapeHtmlAttr(implode(' ', $this->classes));?>" name="<?php echo $this->escapeHtmlAttr($this->name);?>" id="<?php echo $this->escapeHtmlAttr($this->id);?>">
    <?php if ($this->showBlank): ?>
    <option value=""><?php echo $this->escapeHtml($this->blankTitle);?></option>
    <?php endif; ?>

    <?php
    foreach ($this->options as $value => $title) {
        printf(
            '<option value="%s"%s>%s</option>',
            $this->escapeHtmlAttr($value),
            ($this->value === (string) $value ? ' selected="selected"' : ''),
            $this->escapeHtml($title)
        );
    }
    ?>
</select>
