<ul>
    <?php
    foreach ($this->options as $value => $title) {
        echo '<li>';

        printf(
            '<input type="checkbox" name="%s[]" id="%s_%s" value="%s" %s />',
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($value),
            $this->escapeHtmlAttr($value),
            (in_array($value, $this->value) ? 'checked="checked"' : '')
        );

        printf(
            '<label for="%s_%s"> %s</label>',
            $this->escapeHtmlAttr($this->name),
            $this->escapeHtmlAttr($value),
            $this->escapeHtml($title)
        );

        echo '</li>';
    }
    ?>
</ul>
