<div>
    <?php
    if ($this->value) {
        echo '<div class="row">';
        echo '<div class="col-md-4">';
        echo '<span class="thumbnail">';

        printf(
            '<img src="%s" alt="" />',
            $this->escapeHtmlAttr($this->value)
        );

        echo '</span>';
        echo '</div>';
        echo '</div>';
    }
    ?>
    <input type="hidden" name="<?php echo $this->escapeHtmlAttr($this->name);?>" id="<?php echo $this->escapeHtmlAttr($this->id);?>" value="<?php echo $this->escapeHtmlAttr($this->value);?>" />
    <button class="btn btn-default dewdrop-image-picker" type="button" data-target="#<?php echo $this->escapeHtmlAttr($this->id);?>">Select Image</button>
</div>
