<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo $this->escapeHtml($this->title);?></title>

        <?php
        foreach ($this->dependencies['css'] as $css) {
            printf('<link href="%s" rel="stylesheet" />', $this->bowerUrl($css));
        }
        ?>

        <?php
        if ($this->viewHeadLink) {
            echo $this->viewHeadLink;
        }
        ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <?php
    $envClass = '';

    if (defined('APPLICATION_ENV')) {
        $envClass = 'env-' . APPLICATION_ENV;
    }
    ?>
    <body class="<?php echo $envClass;?>">
    <div class="container-fluid">
        <nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#admin-nav-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/admin/"><?php echo $this->escapeHtml($this->title);?></a>
                </div>

                <div class="collapse navbar-collapse" id="admin-nav-collapse">
                    <ul class="nav navbar-nav">
                        <?php
                        foreach ($this->components as $component) {
                            if (!$component->getPermissions()->can('access') || !$component->getPermissions()->can('display-menu')) {
                                continue;
                            }

                            $submenuPages = $component->getSubmenuPages();

                            if (0 === count($submenuPages)) {
                                printf(
                                    '<li><a href="/admin/%s">%s</a></li>',
                                    $this->escapeHtmlAttr($component->getName()),
                                    $this->escapeHtml($component->getTitle())
                                );
                            } else {
                                echo '<li class="dropdown">';

                                printf(
                                    '<a href="#" class="dropdown-toggle" data-toggle="dropdown">%s <b class="caret"></b></a>',
                                    $this->escapeHtml($component->getTitle())
                                );

                                echo '<ul class="dropdown-menu">';

                                foreach ($submenuPages as $page) {
                                    if (isset($page['isDivider']) && $page['isDivider']) {
                                        echo '<li class="divider"></li>';
                                    } else {
                                        printf(
                                            '<li><a href="%s">%s</a></li>',
                                            $this->escapeHtmlAttr($page['url']),
                                            $this->escapeHtml($page['title'])
                                        );
                                    }
                                }

                                echo '</ul>';

                                echo '</li>';
                            }
                        }
                        ?>
                    </ul>
                    <?php if ($this->user):?>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $this->escapeHtml($this->user->getShortName());?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="/admin/users/edit?user_id=<?php echo $this->escapeHtmlAttr($this->user->getId());?>">Account Info</a></li>
                                <li><a href="/admin/users/change-password?user_id=<?php echo $this->escapeHtmlAttr($this->user->getId());?>">Change Password</a></li>
                                <li class="divider"></li>
                                <li><a href="/admin/logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php endif;?>
                </div>
            </div>
        </nav>

        <?php echo $this->content;?>

        <?php
        foreach ($this->dependencies['js'] as $js) {
            printf('<script src="%s"></script>', $this->bowerUrl($js));
        }
        ?>

        <script type="text/javascript">
            jQuery.fn.animate = jQuery.fn.velocity;
        </script>

        <?php
        if ($this->viewHeadScript) {
            echo $this->viewHeadScript;
        }
        ?>
    </body>
</html>
