<?php

echo $this->document()->open('Reset Password');
echo $this->content()->open();
echo $this->h1($this->title);
echo $this->p('We received a request to reset the password for your account.  Please follow the instructions below to complete the reset.');
echo $this->h2('Reset Password');
echo $this->p('Reset your password by following the link button below:');
echo $this->button('Reset Password', $this->resetPasswordUrl);
echo $this->content()->close();
echo $this->document()->close();

