-- This script was generated by the gen-eav command.  You can add additional
-- columns to the attributes table to support application-specific attribute
-- features.  For example, if attributes in your EAV setup are tied to specific
-- accounts (e.g. in a SaaS offering that allows users to create custom fields),
-- you can add an account_id column to your attributes table prior to running
-- dbdeploy.

CREATE TABLE {{tableName}}_eav_attributes (
    attribute_id INTEGER PRIMARY KEY AUTO_INCREMENT,
    backend_type VARCHAR(16) NOT NULL,
    display_helper VARCHAR(64) NOT NULL,
    edit_helper VARCHAR(64) NOT NULL,
    label VARCHAR(255),
    note VARCHAR(255),
    is_required TINYINT(1) NOT NULL DEFAULT 0,
    default_value TEXT
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_varchar (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value VARCHAR(255),{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_text (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value TEXT,{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_datetime (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value DATETIME,{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_decimal (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value DECIMAL(12,4),{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_int (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value INTEGER,{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE {{tableName}}_eav_values_boolean (
    {{primaryKeyColumns}}
    attribute_id INTEGER NOT NULL,
    value BOOLEAN,{{multiColumnPrimaryKeyIndexes}}
    INDEX (attribute_id),
    {{primaryKeyForeignKeys}}
    PRIMARY KEY ({{primaryKeyColumnList}}, attribute_id)
) ENGINE=InnoDB CHARSET=utf8;
