-- This script was generated by the gen-db-table command.  In order to
-- run dbdeploy, you'll need to delete the following line after adding
-- your table's columns:

DBDEPLOY BLOCKED UNTIL THIS LINE REMOVED!

CREATE TABLE {{tableName}} (
    {{primaryKey}} INTEGER PRIMARY KEY AUTO_INCREMENT
) ENGINE=InnoDb CHARSET=utf8;
