<form action="/admin/login-check" method="post">

    <div class="login-error"><?php echo $this->escapeHtml($this->error); ?></div>

    <div>
        <label for="username">Username</label>
        <input id="username" type="text" name="_username"
            value="<?php echo $this->escapeHtmlAttr($this->last_username); ?>" />
    </div>

    <div>
        <label for="password">Password</label>
        <input id="password" type="password" name="_password" value="" />
    </div>

    <button type="submit">Login</button>

</form>
