<nav class="navbar navbar-default navbar-admin-index" role="navigation">
    <div class="navbar-header">
        <a data-keyboard-role="create" href="<?php echo $this->escapeHtmlAttr($this->adminUrl('edit'));?>" class="btn btn-primary navbar-btn">Add <?php echo $this->escapeHtml($this->singularTitle);?></a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#admin-index-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="admin-index-collapse">
        <a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('export', array('format' => 'csv')));?>" class="btn btn-link btn-link-first navbar-btn">Export</a>
        <a href="#" data-toggle="modal" data-target="#adjust-columns-modal" class="btn btn-link navbar-btn">Adjust Columns</a>
        <div class="navbar-right navbar-right-btn-group">
            <div class="btn-group btn-group-justified">
                <div class="btn-group">
                    <button data-keyboard-role="filter" type="button" class="btn btn-default navbar-btn" data-toggle="collapse" data-target="#admin-filter-panel"><span class="glyphicon glyphicon-filter"></span> Filter</button>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-default admin-btn-settings navbar-btn" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Settings <span class="caret"></span></button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Save Current View</a></li>
                        <li><a href="#">Manage Custom Views</a></li>
                        <li><a href="#">Sort and Group Fields</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('notifications'));?>">Notifications</a></li>
                        <li><a data-toggle="modal" data-target="#keyboard-shortcuts-modal" href="#">View Keyboard Shortcuts</a></li>

                        <?php if ($this->debug):?>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation" class="dropdown-header"><span class="glyphicon glyphicon-wrench"></span> Dev Tools</li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-fields'));?>">View Fields</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-listing-sql', $this->getRequest()->getQuery()));?>">View Listing SQL</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-pages'));?>">View Pages</a></li>
                        <li><a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('debug-test-sorting'));?>">Test Sorting</a></li>
                        <?php endif;?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="admin-filter-panel" class="panel panel-default admin-filter-panel collapse">
    <div class="panel-body">
        <form action="" method="GET">
            <div class="text-muted">
                <small>
                    Find <?php echo $this->escapeHtml(strtolower($this->pluralTitle));?> matching
                    <select name="filter_operand">
                        <option value="all">all</option>
                        <option value="any">any</option>
                    </select>
                    of these filters.
                </small>
            </div>
            <fieldset>
                <div class="row">
                    <div class="col-sm-4">
                        <select class="form-control input-sm" name="filters[]">
                            <option value="" disabled="disabled" selected="selected">Select a field to filter by...</option>
                            <?php
                            foreach ($this->fields->getFilterableFields() as $field) {
                                printf(
                                    '<option value="%s">%s</option>',
                                    $this->escapeHtmlAttr($field->getId()),
                                    $this->escapeHtml($field->getLabel())
                                );
                            }
                            ?>
                        </select>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-inline">
                            <span class="glyphicon glyphicon-arrow-right visible-xs"></span>
                            <input class="form-control input-sm" type="date" />
                            <div class="pull-right btn-group">
                                <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"></span></button>
                                <button type="button" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-minus"></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="footer">
                <input type="submit" class="btn btn-success btn-sm" value="Apply Filters" />
                <a class="btn btn-link btn-sm" href="<?php echo $this->escapeHtmlAttr($this->adminUrl('index'));?>">Clear Filters</a>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="keyboard-shortcuts-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Keyboard Shortcuts</h4>
            </div>
            <div class="modal-body">
                <p>
                    When viewing the main <?php echo $this->escapeHtml($this->component->getTitle());?> page,
                    you can use the following keyboard shortcuts to navigate more quickly.
                </p>
                <ul class="list-group">
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">C</button>
                        Create <?php echo $this->escapeHtml($this->singularTitle);?>
                    </li>
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">J</button>
                        Select Next <?php echo $this->escapeHtml($this->singularTitle);?>
                    </li>
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">K</button>
                        Select Previous <?php echo $this->escapeHtml($this->singularTitle);?>
                    </li>
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">E</button>
                        Edit Selected <?php echo $this->escapeHtml($this->singularTitle);?>
                    </li>
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">V</button>
                        View Selected <?php echo $this->escapeHtml($this->singularTitle);?>
                    </li>
                    <li class="list-group-item">
                        <button type="button" class="btn btn-default">/</button>
                        Show Filters
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php
$renderer   = $this->tableCellRenderer();
$fields     = $this->fields->getVisibleFields($this->visibilityFilter);
$firstField = $fields->getIterator()->current();

$renderer->getContentRenderer()
    ->assignCallbackByColumnPosition(
        0,
        function ($helper, $rowData, $rowIndex, $columnIndex) use ($renderer, $firstField) {
            $out = call_user_func(
                $renderer->getContentRenderer()->getFieldAssignment($firstField),
                $rowData,
                $rowIndex,
                $columnIndex
            );

            $primaryKeyValue = array();

            foreach ($this->primaryKey as $field) {
                $primaryKeyValue[$field] = $rowData[$field];
            }

            return $this->partial(
                'index-row-actions.phtml',
                array(
                    'content'       => $out,
                    'params'        => $primaryKeyValue,
                    'singularTitle' => $this->singularTitle
                )
            );
        }
    );

echo $this->bootstrapTable(
    $fields,
    $this->listing->fetchData($this->fields),
    $renderer,
    $this->listing->getSelectModifierByName('SelectSort')
);

echo $this->bootstrapColumnsModal(
    $this->fields,
    $this->fields->getVisibleFields($this->visibilityFilter),
    $this->adminUrl('adjust-visibility')
);

$this->headScript()->appendFile('/js/stock/listing-keyboard-shortcuts.js');
$this->headScript()->appendFile('/js/stock/modal-view.js');
?>
