<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">View <?php echo $this->escapeHtml($this->singularTitle);?></h4>
</div>
<div class="modal-body">
    <nav class="navbar navbar-default navbar-admin-index" role="navigation">
        <div class="navbar-header">
            <a href="<?php echo $this->escapeHtmlAttr($this->adminUrl('edit', $this->params));?>" class="btn btn-primary navbar-btn">Edit <?php echo $this->escapeHtml($this->singularTitle);?></a>
        </div>
    </nav>

    <?php echo $this->bootstrapDetailsView($this->fields, $this->data);?>
</div>
